### PR TITLE
SIREN ND280+ MODULE ADDITION

### PR DESCRIPTION
**Pull request by mingshauliu**
The density and material files are done and checked, I presented the Mathematica 'CAD' in GM but I can automate that too. 

The injection uses high energy supernova in the deep-inelastic scattering example.

### CODE REVIEW

**Comment by mingshauliu** [comment]
VISUAL INTERFACE CREATED FOR MATHEMATICA IN /resources/Detectors/visuals/

**Review by nickkamp1 — COMMENTED** [review]
@mingshauliu most of the changes look good! there are a few extraneous files that should be removed before merging (e.g., all the ".DS_Store" files and the "test_jul20.ipynb" file). Also could you revert the changes to the PaperPlots notebooks? I would like those to remain consistent with the paper. You can keep the DipolePortal_ND280UPGR.py file though, that will be useful for users

**Review by nickkamp1 — CHANGES_REQUESTED** [review]
After changes in above comment I will approve this PR. @austinschneider feel free to add any comments you might have though

**Comment by austinschneider** [comment]
I agree with @nickkamp1 's comments. As far as the extraneous files go, I think they either need to be removed from the history or we can do a squash merge to keep them out of the history.

**Review by mingshauliu — COMMENTED** [review]
All checked!

**Review by nickkamp1 — APPROVED** [review]
looks good to me know, approving! Thanks @mingshauliu

**Comment by nickkamp1** [comment]
> I agree with @nickkamp1 's comments. As far as the extraneous files go, I think they either need to be removed from the history or we can do a squash merge to keep them out of the history.

Makes sense to me. Let's do a squash merge

**Pull request merged**
